services:
  doc:
    image: redocly/openapi-cli:v1.0.0-beta.114
    ports:
      - "8080:8080"
    command: preview-docs /mnt/expanded/openapi.yaml --use-community-edition
    volumes:
      - ".:/mnt"
