openapi: 3.0.1

info:
  title: Re:paint API
  description: API for Re:paint
  version: 2.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3003
    description: Local server

tags:
  - name: admin
    description: API for administrators
  - name: visitor
    description: API for visitors
  - name: auth
    description: API for authentication

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security: []

paths:
  /admin/register:
    $ref: ./path/admin/register.yaml
  /admin/send-email:
    $ref: ./path/admin/send-email.yaml
  /admin/add-operator:
    $ref: ./path/admin/add-operator.yaml
  /admin/event/create:
    $ref: ./path/admin/event/create.yaml
  /admin/event/{eventID}/delete:
    $ref: ./path/admin/event/delete.yaml
  /admin/event/list:
    $ref: ./path/admin/event/list.yaml
  /admin/event/{eventID}/update:
    $ref: ./path/admin/event/update.yaml
  /admin/event/{eventID}/image/register-default:
    $ref: ./path/admin/event/image/register-default.yaml
  /admin/event/{eventID}/image/delete-default:
    $ref: ./path/admin/event/image/delete-default.yaml
  /admin/event/{eventID}/image/check-visitor:
    $ref: ./path/admin/event/image/check-visitor.yaml
  /admin/event/{eventID}/image/upload-visitor:
    $ref: ./path/admin/event/image/upload-visitor.yaml
  /admin/event/{eventID}/image/update-notification:
    $ref: ./path/admin/event/image/update-notification.yaml
  /admin/event/{eventID}/image/proxy:
    $ref: ./path/admin/event/image/proxy.yaml
  /visitor/{visitorID}/image/list:
    $ref: ./path/visitor/image/list.yaml
  /visitor/{visitorID}/image/get-current:
    $ref: ./path/visitor/image/get-current.yaml
  /visitor/{visitorID}/image/set-current:
    $ref: ./path/visitor/image/set-current.yaml
  /visitor/{visitorID}/image/proxy:
    $ref: ./path/visitor/image/proxy.yaml
  /visitor/{visitorID}/image/check-update:
    $ref: ./path/visitor/image/check-update.yaml
  /visitor/{visitorID}/palette/pick:
    $ref: ./path/visitor/palette/pick.yaml
  /visitor/{visitorID}/palette/complete:
    $ref: ./path/visitor/palette/complete.yaml
  /admin/event/{eventID}/spot/register:
    $ref: ./path/admin/event/spot/register.yaml
  /admin/event/{eventID}/spot/check-by-beacon:
    $ref: ./path/admin/event/spot/check-by-beacon.yaml
  /admin/event/{eventID}/spot/check-by-qr:
    $ref: ./path/admin/event/spot/check-by-qr.yaml
  /admin/event/{eventID}/spot/list:
    $ref: ./path/admin/event/spot/list.yaml
  /admin/event/{eventID}/spot/update:
    $ref: ./path/admin/event/spot/update.yaml
  /admin/event/{eventID}/spot/delete:
    $ref: ./path/admin/event/spot/delete.yaml
  /visitor/{visitorID}/spot/scanned:
    $ref: ./path/visitor/spot/scanned.yaml
  /admin/event/{eventID}/traffic/get-status:
    $ref: ./path/admin/event/traffic/get-status.yaml
  /admin/event/{eventID}/traffic/enable-bonus:
    $ref: ./path/admin/event/traffic/enable-bonus.yaml
  /admin/event/{eventID}/traffic/disable-bonus:
    $ref: ./path/admin/event/traffic/disable-bonus.yaml
  /visitor/join:
    $ref: ./path/visitor/join.yaml
  /visitor/{visitorID}/initialize:
    $ref: ./path/visitor/initialize.yaml
  /visitor/{visitorID}/delete:
    $ref: ./path/visitor/delete.yaml
