openapi: 3.0.1

info:
  title: Re:paint API
  description: API for Re:paint
  version: "2.0.0"
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3003
    description: Local server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security: []

paths:
  /admin/register:
    $ref: ./path/admin/register.yaml
  /admin/event/{eventID}/send-email:
    $ref: ./path/admin/event/send-email.yaml
  /admin/add-operator:
    $ref: ./path/admin/add-operator.yaml
  /admin/event/create:
    $ref: ./path/admin/event/create.yaml
  /admin/event/{eventID}/delete:
    $ref: ./path/admin/event/delete.yaml
  /admin/event/list:
    $ref: ./path/admin/event/list.yaml
  /admin/event/{eventID}/update:
    $ref: ./path/admin/event/update.yaml
