openapi: 3.0.1

info:
  title: Re:paint API
  description: API for Re:paint
  version: "1.0.0"
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3003
    description: Local server

security: []

paths:
  /admin/event/{eventID}/spot/register:
    $ref: ./path/admin/event/spot/register.yaml

  /admin/event/{eventID}/spot/check/beacon:
    $ref: ./path/admin/event/spot/check/beacon.yaml

  /admin/event/{eventID}/spot/{spotID}/check/qr:
    $ref: ./path/admin/event/spot/check/qr.yaml

  /admin/event/{eventID}/spot/list:
    $ref: ./path/admin/event/spot/list.yaml

  /admin/event/{eventID}/spot/{spotID}/delete:
    $ref: ./path/admin/event/spot/delete.yaml

  /admin/event/{eventID}/spot/{spotID}/qr:
    $ref: ./path/admin/event/spot/qr.yaml

  /admin/event/create:
    $ref: ./path/admin/event/create.yaml
