openapi: 3.0.1

info:
  title: Re:paint API
  description: API for Re:paint
  version: 2.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3003
    description: Local server

tags:
  - name: admin
    description: API for administrators
  - name: visitor
    description: API for visitors
  - name: auth
    description: API for authentication

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security: []

paths:
  /admin/register:
    $ref: ./path/admin/register.yaml
  /admin/event/{eventID}/send-email:
    $ref: ./path/admin/event/send-email.yaml
  /admin/add-operator:
    $ref: ./path/admin/add-operator.yaml
  /admin/event/create:
    $ref: ./path/admin/event/create.yaml
  /admin/event/{eventID}/delete:
    $ref: ./path/admin/event/delete.yaml
  /admin/event/list:
    $ref: ./path/admin/event/list.yaml
  /admin/event/{eventID}/update:
    $ref: ./path/admin/event/update.yaml
  /admin/event/{eventID}/image/register-default:
    $ref: ./path/admin/event/image/register-default.yaml
  /admin/event/{eventID}/image/delete-default:
    $ref: ./path/admin/event/image/delete-default.yaml
  /admin/event/{eventID}/image/check-visitor:
    $ref: ./path/admin/event/image/check-visitor.yaml
  /admin/event/{eventID}/image/upload-visitor:
    $ref: ./path/admin/event/image/upload-visitor.yaml
  /visitor/{visitorID}/event/{eventID}/image/list:
    $ref: ./path/visitor/event/image/list.yaml
  /visitor/{visitorID}/event/{eventID}/image/get-current:
    $ref: ./path/visitor/event/image/get-current.yaml
  /visitor/{visitorID}/event/{eventID}/image/set-current:
    $ref: ./path/visitor/event/image/set-current.yaml
  /visitor/{visitorID}/event/{eventID}/palette/drop:
    $ref: ./path/visitor/event/palette/drop.yaml
  /visitor/{visitorID}/event/{eventID}/palette/pick:
    $ref: ./path/visitor/event/palette/pick.yaml
