openapi: 3.0.1

info:
  title: Re:paint API
  description: API for Re:paint
  version: "1.0.0"
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3003
    description: Local server

security: []

paths:
  /admin/event/{eventID}/spot/register:
    $ref: ./path/admin/event/spot/register.yaml

  /admin/event/{eventID}/spot/check/beacon:
    $ref: ./path/admin/event/spot/check/beacon.yaml

  /admin/event/{eventID}/spot/check/qr:
    $ref: ./path/admin/event/spot/check/qr.yaml

  /admin/event/{eventID}/spot/list:
    $ref: ./path/admin/event/spot/list.yaml

  /admin/event/{eventID}/spot/{spotID}/delete:
    $ref: ./path/admin/event/spot/delete.yaml

  /admin/event/{eventID}/spot/{spotID}/qr:
    $ref: ./path/admin/event/spot/qr.yaml

  /admin/event/create:
    $ref: ./path/admin/event/create.yaml

  /admin/{adminID}/event/{eventID}/list:
    $ref: ./path/admin/event/list.yaml

  /admin/event/{eventID}/update:
    $ref: ./path/admin/event/update.yaml

  /admin/event/{eventID}/add-operator:
    $ref: ./path/admin/event/add-operator.yaml

  /admin/event/{eventID}/qr:
    $ref: ./path/admin/event/qr.yaml

  /admin/event/{eventID}/notification:
    $ref: ./path/admin/event/notification.yaml

  /admin/event/{eventID}/delete:
    $ref: ./path/admin/event/delete.yaml

  /admin/event/{eventID}/default-image:
    $ref: ./path/admin/event/default-image.yaml

  /admin/event/{eventID}/traffic/status:
    $ref: ./path/admin/event/traffic/status.yaml

  /admin/event/{eventID}/traffic/control:
    $ref: ./path/admin/event/traffic/control.yaml

  /admin/event/{eventID}/visitor/{visitorID}/check:
    $ref: ./path/admin/event/visitor/check.yaml

  /admin/event/{eventID}/visitor/{visitorID}/photo:
    $ref: ./path/admin/event/visitor/photo.yaml

  /visitor/event/join:
    $ref: ./path/visitor/event/join.yaml

  /visitor/{visitorID}/event/{eventID}/qr:
    $ref: ./path/visitor/event/qr.yaml

  /visitor/{visitorID}/event/{eventID}/startup:
    $ref: ./path/visitor/event/startup.yaml

  /visitor/{visitorID}/event/{eventID}/notification:
    $ref: ./path/visitor/event/notification.yaml

  /visitor/{visitorID}/event/{eventID}/delete:
    $ref: ./path/visitor/event/delete.yaml

  /visitor/{visitorID}/event/{eventID}/image/list:
    $ref: ./path/visitor/event/image/list.yaml

  /visitor/{visitorID}/event/{eventID}/image/select:
    $ref: ./path/visitor/event/image/select.yaml

  /visitor/{visitorID}/event/{eventID}/image/current:
    $ref: ./path/visitor/event/image/current.yaml

  /visitor/{visitorID}/event/{eventID}/spot/drop:
    $ref: ./path/visitor/event/spot/drop.yaml

  /visitor/{visitorID}/event/{eventID}/spot/pick:
    $ref: ./path/visitor/event/spot/pick.yaml
