name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: re-taro/actions/setup-node@v1.0.0
        with:
          node-version-file: .tool-versions
      - name: check formatting
        run: pnpm _format --check
      - name: run linter
        run: pnpm lint
