name: github pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: re-taro/actions/setup-node@v1.0.0
        with:
          node-version-file: .tool-versions
      - name: bundle
        run: |
          pnpm bundle
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./docs"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
